sudo: false
dist: xenial
language: python

git:
  depth: false

python:
  - "3.5"
  - "3.6"
  - "3.7"

cache:
  pip: true
  directories:
    - node_modules
      - $HOME/.cache/pip
      - $HOME/.cache/pre-commit

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env:
        - TEST_PRECOMMIT="true"

install:
  - pip install pytest-xdist tox-travis codecov coverage $django
  - >
    if [ -n "$TEST_PRECOMMIT" ]; then
      pip install pre-commit
    else
      ./setup.py develop \
      && pip install -e .[dev]
    fi

script:
  - >
    if [ -n "$TEST_PRECOMMIT" ]; then
      pre-commit run --all-files
    else
      coverage run --source draftjs_sanitizer -m pytest
    fi

after_success: codecov
